#!/bin/sh

opkg install libboost-python35-1.68.0
opkg install libpython3.5m-staticdev
opkg install libpython3.5m1.0
opkg install python3-2to3
opkg install python3-asyncio
opkg install python3-audio
opkg install python3-codecs
opkg install python3-compile
opkg install python3-compression
opkg install python3-core
opkg install python3-crypt
opkg install python3-ctypes
opkg install python3-curses
opkg install python3-datetime
opkg install python3-db
opkg install python3-debugger
opkg install python3-difflib
opkg install python3-distutils
opkg install python3-doctest
opkg install python3-email
opkg install python3-fcntl
opkg install python3-gdbm
opkg install python3-html
opkg install python3-idle
opkg install python3-image
opkg install python3-io
opkg install python3-json
opkg install python3-libcec
opkg install python3-logging
opkg install python3-mailbox
opkg install python3-math
opkg install python3-mime
opkg install python3-misc
opkg install python3-mmap
opkg install python3-modules
opkg install python3-multiprocessing
opkg install python3-netclient
opkg install python3-netserver
opkg install python3-numbers
opkg install python3-pickle
opkg install python3-pkgutil
opkg install python3-plistlib
opkg install python3-pprint
opkg install python3-profile
opkg install python3-pydoc
opkg install python3-resource
opkg install python3-runpy
opkg install python3-shell
opkg install python3-smtpd
opkg install python3-sqlite3
opkg install python3-stringold
opkg install python3-syslog
opkg install python3-terminal
opkg install python3-threading
opkg install python3-tkinter
opkg install python3-typing
opkg install python3-unittest
opkg install python3-unixadmin
opkg install python3-venv
opkg install python3-xml
opkg install python3-xmlrpc
